# fly.toml app configuration file generated for palette on 2023-10-21T19:46:56+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "palette"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
